### ISSUE TITLE
[feat]: 일정 상세보기 페이지 구현

### ISSUE THREAD

**Issue by hongii** [7days-routrip/routrip#10]
## 📝 작업할 내용
일정 상세보기 페이지 구현

## ✅ To-do

- [x] 수정 버튼 클릭 시 일정 수정 페이지로 이동 & 해당 일정 데이터 불러오기
- [x] 일정 삭제 기능 구현 → 삭제 버튼 클릭 시 confirm 창을 통해 사용자의 이벤트를 받고 삭제 요청 보내기
- [x] 일정 제목 & 여행한 날짜 데이터 불러오기
- [x] 각 날짜 별로 첫 번째 장소에 해당하는 위치를 마커로 찍은 지도 띄우기

### Figma UI 디자인
- 일정 상세 보기 페이지
![image](https://github.com/7days-routrip/routrip/assets/93701887/510d9343-9f7e-4b86-85f4-0b80b47348ee)
