### ISSUE TITLE
[feat]: 배포 작업

### ISSUE THREAD

**Issue by 6uamy** [7days-routrip/routrip#177]
## 📝 작업할 내용

EC2 인스턴스에 프로젝트 배포

## ✅ To-do

- [ ] Dockerfile 작성 (client, server)
- [ ] docker-compose.yml 작성
- [ ] EC2 인스턴스에 compose up
