### ISSUE TITLE
[deploy]: 서버 package.json, tsconfig.json 빌드 용 설정 추가

### ISSUE THREAD

**Issue by jh9788** [7days-routrip/routrip#215]
## 📝 작업할 내용

- 서버측 빌드와 빌드된 코드 실행을 위해 설정을 추가한다.

## ✅ To-do

- [x] build 명령어 추가
- [x] production 코드 실행 명령어 추가
- [x] ts-node 설정 추가

## 🔎 참고 사항

- npm run product 명령어에서는 "nodemon --exec \"ts-node -r tsconfig-paths/register ./dist\"" 과 같이 nodemon 방식이 아닌 단순 ts-node 방식 채택
