### ISSUE TITLE
[feat]: 글쓰기 및 top 버튼 컴포넌트 구현

### ISSUE THREAD

**Issue by kim-hong-rae** [7days-routrip/routrip#38]
## 📝 작업할 내용

글쓰기 및 top 버튼 컴포넌트 구현

## ✅ To-do

- [x] 글쓰기 버튼 구현
- [ ] top 버튼 구현
- [x] 특정 조건에서만 글쓰기 버튼 및 top버튼 같이 보이게, 그 외에는 top버튼만 보이게

## 📷 스크린샷

<img width="143" alt="스크린샷 2024-05-02 오전 4 48 26" src="https://github.com/7days-routrip/routrip/assets/102844071/43b6e986-d5aa-490a-90a7-a658d6faf920">
