### ISSUE TITLE
[feat]: client 초기 환경 구축

### ISSUE THREAD

**Issue by hongii** [7days-routrip/routrip#5]
## 📝 작업할 내용
- client 초기 환경 구축
  - 프로젝트 생성 : `Vite`
  - 패키지 매니저 : `npm`
- global css, theme 설정
- 샘플 코드 작성

## ✅ To-do

- [x] ESLint & Prettier 설정
- [x] 필요한 라이브러리 설치
- [x] 절대 경로 설정
- [x] 폴더 구조 생성
- [x] 라우터 설정
- [x] 공통 아이콘 파일 생성
- [x] global theme 객체 생성
- [x] global css 설정
- [x] logo 이미지 파일 삽입
- [x] axios 인스턴스 생성
