### ISSUE TITLE
[feat]: 일정 등록 페이지 리팩토링

### ISSUE THREAD

**Issue by hongii** [7days-routrip/routrip#56]
## 📝 작업할 내용
- 각 day마다 관리하는 장소 아이템을 감싸는 컴테이너 영역 부분이 드래그 앤 드롭으로 아이템을 이동시키려고 할 때 이상하게 동작하는 것을 발견해서 수정해야함
  - 아이템을 이동하려고 클릭할 경우, 해당 아이템이 제거된 만큼의 높이로 컨테이너 영역이 줄어드는 문제가 발생함
- 사용자가 잘못된 일정을 선택(여행 종료일이 여행 시작일 보다 앞선 경우)한 상태로 일정 등록 버튼 클릭 시, 해당 요청을 무시하는 로직 추가
- `Place` 모델 재정의
  - 이에 따라, `makeMockPlaces` 유틸 함수도 수정해야함
- 사용자가 이미 여행일정을 선택하여 방문할 장소를 다 배분한 상태에서 다른 여행일정을 클릭하면 이미 배분해뒀던 장소가 전부 사라지는건 사용자 입장에서 불편할 것이라 예상됨 
  - 따라서, 이 경우에는 각 day마다 방문할 장소들을 전부 전역 state로 관리하는 '추가한 장소' 탭으로 이동시키는 로직이 필요하다 생각함
- 여행 시작일과 종료일을 각각 1줄씩 차지하게 했는데, 너무 길어지고 안 예쁜 것 같아서 한 줄에 배치하도록 수정할 예정
## ✅ To-do

- [x] 여행 일정 등록 페이지에서 드래그 앤 드롭 기능에 관련된 코드 리팩토링
- [x] 일정 등록 버튼 클릭 시, 필요한 로직 추가
- [x] 사용자가 잘못된 여행 일정을 선택할 경우, 커스텀 aler창이 보이도록 구현
- [x] `Place` 모델 재정의
- [x]  `makeMockPlaces` 유틸 함수에서, 가짜 장소 데이터를 `SelectedPlace` 타입에 맞게 수정(`Place`를 확장한 타입)
- [x] 사용자가 이미 여행일정을 선택한 후에 각 day 마다 방문할 장소를 추가해둔 상태에서 여행일정을 다시 선택할 경우, 방문할 장소로 담아뒀던 장소들을 전부 다시 '추가한 장소' 탭으로 이동시키는 로직 추가
- [x] 여행 일자를 선택하는 영역 스타일 수정
