### ISSUE TITLE
[feat]: Spots API 리팩토링

### ISSUE THREAD

**Issue by jh9788** [7days-routrip/routrip#69]
## 📝 작업할 내용

spots.ctl 에 있는 코드의 전반적인 리팩토링

## ✅ To-do

- [x] 현재 Controller에 합쳐져 있는 코드를 Service, type 등으로 분리
- [x] 중복 코드 제거
- [x] API 수정사항 반영
