### ISSUE TITLE
[feat]: 일정 등록 페이지 구현 & 기능 구현

### ISSUE THREAD

**Issue by hongii** [7days-routrip/routrip#9]
## 📝 작업할 내용
일정 등록 페이지 구현

## ✅ To-do

- [x] react-google-maps/api 분석
- [x] 구글 지도 화면에 띄우기
- [x] 구글 지도를 움직이거나 zoom-in, zoom-out을 할 경우, 현재 보이는 지도의 중심점 좌표를 갱신하는 기능 구현
- [x] 날짜 별 선택한 장소의 위치를 구글 지도에 마커로 표시하기
- [x] "추가한 장소"탭 클릭 시 해당 탭 영역에 담겨진 장소 아이템들을 마커로 표시하기
- [x] 장소 검색 기능 구현(api 서버로 요청)
- [x] 신규 장소 등록에서 검색 기능 구현(google map api로 주변 장소 검색 요청)
- [x] 신규 장소 등록 기능 구현
  - 백엔드 서버로 중복 장소체크 요청 먼저 보냄 → 200 OK 일 경우, google map api로 장소 디테일 정보 요청 → 받은 데이터를 담아서 백엔드 서버로 신규 장소 등록 요청
  - 백엔드 서버로 중복 장소체크 요청 먼저 보냄 → 409 Conflict 일 경우, 백엔드 서버로 장소 디테일 정보 요청
- [x] 제목 input 추가
- [x] 날짜 선택 input 추가
- [x] 일정 등록 장소 검색 및 신규 장소 등록 탭 컴포넌트 구현
- [x] 장소 선택 및 내가 찜한 장소 탭 컴포넌트 구현
- [x] 내가 찜한 장소 불러오기 기능 구현
- [x] ~~react-beautiful-dnd 라이브러리 분석(드래그앤 드롭)~~ → 해당 라이브러리 버전 호환 오류 발생
- [x] hello-pangea/dnd 라이브러리를 사용한 드래그앤 드롭 기능 구현
- [x] 추가한 장소를 각 날짜 별 일정 컴포넌트와 드래그앤 드롭 기능을 통해 자유롭게 설정되도록 구현
- [x] 날짜 안에서 선택한 장소 순서를 드래그앤 드롭 기능으로 자유롭게 설정되도록 구현
- [ ] 각 일정에 포함된 장소 아이템 전체를 이동 가능하도록 드래그앤 드롭 기능 구현 
- [ ] 각 날짜 별 숙소 선택 기능 구현(숙소는 날짜 별로 1개만 선택 가능, 하나 선택 이후 다시 선택할 경우 기존 숙소 정보는 사라지고 새로운 숙소 정보로 갱신) → 추후 고도화 가능하다면 해당  기능 추가하는 것으로 계획 수정
- [x] 일정 등록 기능 구현(서버 요청)
- [x] 장소 추가는 중복 추가 가능하도록 구현
- [x] uuid 라이브러리 설치하여 중복 추가된 장소더라도 구분해서 삭제하도록 기능 추가
- [x] zustand store를 이용하여 추가된 일정을 전역으로 관리
- [x] 사용자가 새로고침 버튼 클릭 시, confirm창으로 사용자의 선택 값을 받도록 설정
- [x] faker 라이브러리 설치 및 추가된 장소에 대한 더미 데이터 배열을 생성하는 유틸함수 구현

### Figma UI 디자인
- 일정 등록 페이지
![image](https://github.com/7days-routrip/routrip/assets/93701887/ddb22dd6-937f-4e04-8d46-3f63ba180591)
- 장소 선택 및 내가 찜한 장소 탭 컴포넌트 & 일정 등록 장소 검색 및 신규 장소 등록 탭 컴포넌트
![image](https://github.com/7days-routrip/routrip/assets/93701887/4cad7d34-b4cc-4e8d-a5cc-48637a666a2d)
