### ISSUE TITLE
[feat]: 일정 등록 페이지에서 지도에 보여주는 마커 표시 세분화 작업

### ISSUE THREAD

**Issue by hongii** [7days-routrip/routrip#90]
## 📝 작업할 내용

- 기존에 구현한 마커 표시 기능
  - "추가한 장소" 탭 버튼을 클릭하거나, day 영역을 클릭할 경우 각 영역에 포함되어 있는 장소 아이템들의 마커를 전부 표시
  - 장소를 추가하거나 등록할 때 "추가한 장소"탭으로 해당 장소 아이템이 추가되면서 지도에 마커 표시
- 마커 세분화 작업을 통해 추가할 기능
  - "추가한 장소" 탭 버튼과 day영역 클릭할 때 뿐만 아니라, 모든 탭 버튼("장소 선택", "신규 장소 등록", "추가한 장소", "내가 찜한 장소") 또는 각 day영역을 눌렀을 때 해당 영역에 존재하는 장소 아이템들의 마커를 지도에 표시
  - 사용자가 검색 키워드를 통해 검색 기능을 시도(Enter 혹은 Click)했을 때, 검색 결과로 가져와진 장소 아이템들의 마커가 한번에 표시되도록 구현할 예정 

## ✅ To-do

- [x] 내가 찜한 장소 탭 버튼과 장소 검색 및 신규 장소 등록 탭 버튼을 클릭했을 때, 지도에 표시할 마커 아이콘 파일 찾기
- [x] 전역 상태로 관리중인 `markerType`에 신규 장소 등록 타입과 장소 선택 타입, 내가 찜한 장소 타입을 추가
- [x] ScheduleGoogleMap 컴포넌트에 마커 관련 코드 수정
